print('==========')
print('fstring Demo')
print('==========')
name= input('Enter your name:')
age= int(input('Enter your age:'))
branch= input('Enter your branch:')
print(f'Name of student is {name}')
print(f'Age of student is {age}')
print(f'Branch of student is {branch}')
