print('==========')
print('Create Tuple')
print('==========')
fruits= ('Apple', 'Mango', 'Banana')
subjects= ('DS', 'OS', 'DELD')
cities= ('Pune', 'Mumbai', 'Nashik')
print(fruits)
print(subjects)
print(cities)
