name = input("Enter your name: ")
age = input("Enter your age: ")
college = input("Enter your college name: ")
branch = input("Enter your branch: ")
semester = input("Enter your current semester: ")

print("\n==============================")
print("   STUDENT INFORMATION CARD")
print("==============================")
print("Name      :", name)
print("Age       :", age)
print("College   :", college)
print("Branch    :", branch)
print("Semester  :", semester)
print("==============================")
