restaurant_name = input("Enter restaurant name: ")
owner_name = input("Enter owner name: ")
location = input("Enter restaurant location: ")
number_of_employees = input("Enter number of employees: ")
pure_veg = input("Is the restaurant pure veg? (Yes/No): ")

print("\n==============================")
print("  RESTAURANT INFORMATION CARD")
print("==============================")
print("Restaurant Name :", restaurant_name)
print("Owner Name      :", owner_name)
print("Location        :", location)
print("Employees       :", number_of_employees)
print("Pure Veg        :", pure_veg)
print("==============================")
