number1= int(input('Enter number 1:'))
number2= int(input('Enter number 2:'))
print('==========')
print('Calcultor Mini Project')
print('==========')
print('Addition:', number1+number2)
print('Subtraction:', number1-number2)
print('Multiplication:', number1*number2)
print('Division:', number1/number2)
