num1= int(input('Enter a number:'))
num2= int(input('Enter another number:'))
print('==========')
print('Comparison operators')
print('==========')
print('Are both numbers equal:', num1==num2)
print('Are both numbers not equal:', num1!=num2)
print('Is num1 greater than num2:', num1>num2)
print('Is num1 less than num2:', num1<num2)
print('Is num1 greater than or equal to num2:', num1>=num2)
print('Is num1 less than or equal to num2:', num1<=num2)
