number1= int(input('Enter number 1:'))
number2= int(input('Enter number 2:'))
print('==========')
print('Operations on numbers')
print('==========')
print('Addition of numbers:', number1+number2)
print('Subtraction of numbers:', number1-number2)
print('Multiplication of numbers:', number1*number2)
print('Division of numbers:', number1/number2)
print('Floor division of numbers:', number1//number2)
print('Modulus of numbers:', number1%number2)
print('Power of numbers:', number1**number2)
