sub1= int(input('Enter marks for subject 1:'))
sub2= int(input('Enter marks for subject 2:'))
sub3= int(input('Enter marks for subject 3:'))
sub4= int(input('Enter marks for subject 4:'))
sub5= int(input('Enter marks for subject 5:'))
total_marks= int(input('Enter total marks:'))
percentage= ((sub1+sub2+sub3+sub4+sub5)/total_marks)*100
print('==========')
print('Percentage Calculator')
print('==========')
print('The percentage obtained is:', percentage)
